# Credit to https://github.com/openscript/openscript :)


on:
  issue_comment:
    types: [created, edited, deleted]

name: Guestbook

jobs:
  update_guestbook:
    name: Update guestbook
    if: ${{ github.event.issue.title == 'Guestbook' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update guestbook from comments
        uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!, $issue_number:Int!) {
              repository(owner:$owner, name:$name){
                issue(number:$issue_number) {
                  comments(last:10,orderBy:{direction:DESC, field:UPDATED_AT}) {
                    nodes {
                      author {
                        avatarUrl(size: 24)
                        login
                        url
                      }
                      bodyText
                      updatedAt
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.issue.number
            }
            const result = await github.graphql(query, variables)
            const renderComments = (comments) => {
              return comments.reduce((prev, curr) => {
                return `${prev}|[![${curr.author.login}](${curr.author.avatarUrl})${curr.author.login}](${curr.author.url})|${new Date(curr.updatedAt).toLocaleString()}|${curr.bodyText}|\n`;
              }, "| Name | Date | Message |\n|---|---|---|\n");
            };
            const fileSystem = require('fs');
            const readme = fileSystem.readFileSync('README.md', 'utf8');
            fileSystem.writeFileSync('README.md', readme.replace(/(?<=## Guestbook.*\n)[\S\s]*?(?=#|$(?![\n]))/gm, renderComments(result.repository.issue.comments.nodes)), 'utf8');
      - name: Push guestbook update
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '1105080+brunnerlivio@users.noreply.github.com'
          git commit -am 'update guestbook'
          git push
